/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fpt.it17326.nhom5.view;

import com.fpt.it17326.nhom5.repobanhang.banhang_repo;
import com.fpt.it17326.nhom5.viewmodel.banhangimeithoebang;
import com.fpt.it17326.nhom5.viewmodel.sanphambanhang;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHAM DAC THANG
 */
public class banhangimei extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    banhang_repo rp=new banhang_repo();
    int vitridonghd=-1;
    int vitridongsanpham=-1;
    String maspimei=null;
    public banhangimei(java.awt.Frame parent, boolean modal,String masp,int vitrisanpham,int vitridongbanghoadon,String tenbang) {
        super(parent, modal);
        initComponents();
        if (tenbang.equals("sanpham")) {
              loadtablebangimeisanpham(masp);
              btxoaimeibanhang.setEnabled(false);
              btthemimeibanhang.setEnabled(true);
        } else {
            loadtablebangimeigiohang(rp.gethdbanhang().get(vitridongbanghoadon).getMaHD(), masp);
             btthemimeibanhang.setEnabled(false);
              btxoaimeibanhang.setEnabled(true);
        }
      
        vitridonghd=vitridongbanghoadon;
        maspimei=masp;
        vitridongsanpham=vitrisanpham;
    }

     public void loadtablebangimeisanpham(String v){
         DefaultTableModel defaultTable = new DefaultTableModel();
    defaultTable.setRowCount(0);
      defaultTable = (DefaultTableModel) tbbangbanhangimei.getModel();
      defaultTable.setRowCount(0);
        if (rp.imeisanphambanhang(v).size()<0) {
              System.out.println( rp.imeisanphambanhang(v).size());
       } else {
            
            int stt=0;
             for (banhangimeithoebang sv : rp.imeisanphambanhang(v)) {
                
           defaultTable.addRow(new Object[] {
               stt=stt+1,
           sv.getId(),sv.getMaimei(),sv.getImei()
           
           });
       }
       
       }
      
      
    
    }
     
        public void loadtablebangimeigiohang(String mhd,String msp){
         DefaultTableModel defaultTable = new DefaultTableModel();
  
      defaultTable = (DefaultTableModel) tbbangbanhangimei.getModel();
      
      
       tbbangbanhangimei.setModel(defaultTable);
        String[] hearder = {"STT","ID bảng imei đã bán","MaImei","Imei"};
        defaultTable.setColumnIdentifiers(hearder);
      defaultTable.setRowCount(0);
        if (rp.imeigiohangbanhang(mhd,msp).size()<0) {
              System.out.println( rp.imeigiohangbanhang(mhd,msp).size());
       } else {
            
            int stt=0;
             for (banhangimeithoebang sv : rp.imeigiohangbanhang(mhd,msp)) {
                
           defaultTable.addRow(new Object[] {
               stt=stt+1,
           sv.getId(),sv.getMaimei(),sv.getImei()
           
           });
       }
       
       }
      
      
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbangbanhangimei = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btthemimeibanhang = new javax.swing.JButton();
        btxoaimeibanhang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách imei"));

        tbbangbanhangimei.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "ID imei", "MaImei", "Imei"
            }
        ));
        jScrollPane1.setViewportView(tbbangbanhangimei);

        jLabel1.setText("imei");

        btthemimeibanhang.setText("Thêm vào giỏ hàng");
        btthemimeibanhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthemimeibanhangActionPerformed(evt);
            }
        });

        btxoaimeibanhang.setText("Xóa khỏi giỏ hàng");
        btxoaimeibanhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxoaimeibanhangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btxoaimeibanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btthemimeibanhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btxoaimeibanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btthemimeibanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btthemimeibanhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthemimeibanhangActionPerformed
     int hang=tbbangbanhangimei.getSelectedRow();
     int tong=tbbangbanhangimei.getSelectedRowCount();
     
        if (vitridonghd==-1) {
            JOptionPane.showMessageDialog(this,"Bạn chưa chọn hóa đơn để thêm vào giỏ hàng hóa đơn đó");
        }else{
        
            if (rp.gethdbanhang().get(vitridonghd).getTrangthai()==1) {
                JOptionPane.showMessageDialog(this,"Hóa đơn mã : "+rp.gethdbanhang().get(vitridonghd).getMaHD()+"  đã được thanh toán.\n"
                                                  + "Nên bạn không thể thêm sản phẩm");
            } else {
                if ( rp.themhoadonchitietbanhang(
                        rp.gethdbanhang().get(vitridonghd).getId(),
                        rp.getsanphambanhang().get(vitridongsanpham).getId(),
                         rp.getsanphambanhang().get(vitridongsanpham).getTensp()
                        
                        , tong,   rp.getsanphambanhang().get(vitridongsanpham).getDongia()
                )) {
                    
                   
                    int sl=0;
                      for (int i = hang; i < hang+tong; i++) {
                    rp.themimeidaban(rp.imeisanphambanhang(maspimei).get(i).getMaimei(),
                            rp.imeisanphambanhang(maspimei).get(i).getImei(),
                            rp.gethdbanhang().get(vitridonghd).getId(),
                        rp.getsanphambanhang().get(vitridongsanpham).getId()
                    );
                          System.out.println("solh---"+sl);
                }
                
              JOptionPane.showMessageDialog(this,"Thêm thành công"); 
        
           
            
                }else{
                
                JOptionPane.showMessageDialog(this,"lỗi thêm hóa đơn chi tiết");
                }
               
              
            }
        
        }
    }//GEN-LAST:event_btthemimeibanhangActionPerformed

    private void btxoaimeibanhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxoaimeibanhangActionPerformed
        if (rp.gethdbanhang().get(vitridonghd).getTrangthai()==1) {
            JOptionPane.showMessageDialog(this,"MÃ HÓA ĐƠN : "+rp.gethdbanhang().get(vitridonghd).getMaHD()+" ĐÃ THANH TOÁN.\n"
                                             + "NÊN KHÔNG THỂ XÓA THÔNG TIN IMEI ĐÃ BÁN");
        }else{
            
                int hang=tbbangbanhangimei.getSelectedRow();
     int tong=tbbangbanhangimei.getSelectedRowCount();
     for (int i = hang; i < hang+tong; i++) {
                 rp.XOAIMEITRONGBANGIMEIDABAN(tbbangbanhangimei.getValueAt(tbbangbanhangimei.getSelectedRow(),1).toString());
                          System.out.println("solh---"+i);
                }
                
              JOptionPane.showMessageDialog(this,"Xóa Thành công"); 
     
         
        loadtablebangimeigiohang(rp.gethdbanhang().get(vitridonghd).getMaHD(), maspimei);
        
        }
        
     
    }//GEN-LAST:event_btxoaimeibanhangActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(banhangimei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(banhangimei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(banhangimei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(banhangimei.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                banhangimei dialog = new banhangimei(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btthemimeibanhang;
    private javax.swing.JButton btxoaimeibanhang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbbangbanhangimei;
    // End of variables declaration//GEN-END:variables
}
